steps:
  - name: golang
    args: 
      - '-c'
      - >-
        ls -a && ls -a
    waitFor: ["-"]
    entrypoint: /bin/bash
timeout: 86000s
options:
  machineType: E2_HIGHCPU_32
  diskSizeGb: '1000'




